### ISSUE TITLE
main.py got detected

### ISSUE THREAD

**Issue by yo-22** [KDot227/Powershell-Token-Grabber#10]
you said that main.exe is main.py u can compile it.....
i did that but the file always get detected not like the one you uploaded its not detected even when it obfuscated it always get detected
can you tell me how u compile or obfuscate the python script if that possible
ps i used pyinstaller to compile it
ty for the work <3

**Comment by KDot227** [comment]
> you said that main.exe is main.py u can compile it..... i did that but the file always get detected not like the one you uploaded its not detected even when it obfuscated it always get detected can you tell me how u compile or obfuscate the python script if that possible ps i used pyinstaller to compile it ty for the work <3

I used pyarmor with pyinstaller. You can always edit the code and make an exception for your exe though

**Comment by yo-22** [comment]
i did but somehow it still get detected
anyway i'll try it thanks

**Comment by KDot227** [comment]
> i did but somehow it still get detected anyway i'll try it thanks

I can give you my exact pyinstaller command if u want

**Comment by yo-22** [comment]
yes pls

**Comment by KDot227** [comment]
it's something like this. Change the values if u need too

```
pyarmor-7 pack --clean -x " --advanced 5 --no-cross-protection --obf-mod 2 --obf-code 2 --restrict 0" -e " --clean --onefile --noconfirm --key GODFATHER --icon=C:/Users/this1/Desktop/COMPILE/flag.ico" main.py
```
Also use build the pyinstaller bootloader for less detections
