### ISSUE TITLE
Generating and bots

### ISSUE THREAD

**Issue by ZadgeIsCool** [KDot227/Powershell-Token-Grabber#101]
I made a FUD file and 95% of the time when I or someone else click on that file, data does not get sent to the Discord. It works sometimes but sometimes not (95% of the time it does not work). When it FINALLY generates, the KDOT.zip file does not generate (I have only seen it generate with bots which I will talk about now.) My Discord server gets spammed with bots data so please make an "Antibot" option like grabbify where sometimes you see "Google LLC" and that is a bot but when you enable "antibot" it does not show bots. and guess what, bots data generate and generate the KDOT.zip file 80% of the time but real humans data do not.

**Comment by xpierroz** [comment]
frfr

**Comment by KDot227** [comment]
FIXED
