### ISSUE TITLE
BRO

### ISSUE THREAD

**Issue by ANAS765543** [KDot227/Powershell-Token-Grabber#102]
bro what's wrong with your discord server guys my accounts are deleted because i am on your shitty servers i ain't making 3 account add me on here if you want to text me not going to join 
ANAS#9385

**Comment by KDot227** [comment]
Ain't nobody was talking to u either way

**Comment by Resisst** [comment]
aint nobody want to text u mister anus

**Comment by ANAS765543** [comment]
ain't talking to niggas dumb kid
