### ISSUE TITLE
Get rid of external binary and just compile c# function to grab token

### ISSUE THREAD

**Issue by KDot227** [KDot227/Powershell-Token-Grabber#18]
I give up with tryna do it all in powershell

**Comment by Chainski** [comment]
> I give up with tryna do it all in powershell

The Add-Type cmdlet in powershell can be utilized so you can load your .NET assemblies in to memory if your don't want to use the python binary. The [hide-console](https://github.com/KDot227/Powershell-Token-Grabber/blob/main/main.ps1#L241) function is obviously c# code that's loaded into memory at runtime to hide the window after executing the script so, it shouldn't be a difficult task to implement.

**Comment by KDot227** [comment]
> > I give up with tryna do it all in powershell
> 
> The Add-Type cmdlet in powershell can be utilized so you can load your .NET assemblies in to memory if your don't want to use the python binary. The [hide-console](https://github.com/KDot227/Powershell-Token-Grabber/blob/main/main.ps1#L241) function is obviously c# code that's loaded into memory at runtime to hide the window after executing the script so, it shouldn't be a difficult task to implement.

That’s what I was working on but believe it or not idk c# allat well so it’s gonna be a pain but I should have it done hopefully be tomorrow

**Comment by KDot227** [comment]
this never happened
