### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by yo-22** [KDot227/Powershell-Token-Grabber#32]
are you interested in adding an option to generate vba macros that can be embed in word or excel for your powershell grabber?
i already tried it and the word file is 5 / 64 on virustotal and the second phase (.hta file) is 6 / 59 i still didnt try the excel file yet but i did some tests with other payloads and excel files have a higher chance not being detected

**Comment by KDot227** [comment]
> are you interested in adding an option to generate vba macros that can be embed in word or excel for your powershell grabber?
> 
> i already tried it and the word file is 5 / 64 on virustotal and the second phase (.hta file) is 6 / 59 i still didnt try the excel file yet but i did some tests with other payloads and excel files have a higher chance not being detected

Yuh today I'll add those 2 + vbs. Idk if there are any windows maintained langs after that tho unless I start making com files (idk how to do that)

**Comment by yo-22** [comment]
for creating com files u need assembly that the only lang that can be used
i can provide you with the 2 vba macros i created they are basic af (using windows api to create a text file in the startup then using name statement to change the extension from txt to hta) + not obfuscated

**Comment by KDot227** [comment]
> for creating com files u need assembly that the only lang that can be used
> 
> i can provide you with the 2 vba macros i created they are basic af (using windows api to create a text file in the startup then using name statement to change the extension from txt to hta) + not obfuscated

Sure send them

**Comment by KDot227** [comment]
U can join the server I have it linked on https://sped.lol

**Comment by yo-22** [comment]
im already in it my discord is rizi#6164
