### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by Voidrip** [KDot227/Powershell-Token-Grabber#35]
When i create a batch file grabber it says do youw ant to obfuscate and make it FUD so i say yes and it bypasses virus total and hybrid analysis but the exe files and ps1 files dont say do you want to obfuscate4 and when i put it into virus total and hybrid analysis it detects some stuff in it

**Comment by Voidrip** [comment]
So is the EXE and PS1 files obfuscated or do i have to obfuscate myself

**Comment by KDot227** [comment]
> When i create a batch file grabber it says do youw ant to obfuscate and make it FUD so i say yes and it bypasses virus total and hybrid analysis but the exe files and ps1 files dont say do you want to obfuscate4 and when i put it into virus total and hybrid analysis it detects some stuff in it

Power shell obfuscation isnt batch Somalifuscator is only batch
