### ISSUE TITLE
problem in main.py

### ISSUE THREAD

**Issue by yo-22** [KDot227/Powershell-Token-Grabber#41]
the main.py i think theres a problem in it cause aint doing nothing i compiled it as it is without any obfuscation using pyinstaller and upload it and try to run it using powershell but its not working i dont receive anything
im pretty sure the problem from main.py because i checked and its downloaded and been executed but i receive nothing

**Comment by yo-22** [comment]
all it does just extracting token and saving it in tokens.txt thats it

**Comment by KDot227** [comment]
> all it does just extracting token and saving it in tokens.txt thats it

That's what it's supposed to do

**Comment by KDot227** [comment]
Read the code

**Comment by yo-22** [comment]
i did ik its just extract password and u send them using curl.exe
but it supposed to extract passwords which is not doing i also deleted part in powershell part where it delete files after sending them and checked temp and folder where theres powershell folder after running it and there's nothing

**Comment by yo-22** [comment]
nvm its fixed
