### ISSUE TITLE
skidded

### ISSUE THREAD

**Issue by LocalSmail** [KDot227/Powershell-Token-Grabber#44]
fr

**Comment by KDot227** [comment]
For

**Comment by KDot227** [comment]
Real

**Comment by Chainski** [comment]
> fr

While we greatly value your participation and input, we would like to kindly request that you refrain from making negative comments if you do not have any worthwhile contributions to make.

**Comment by LocalSmail** [comment]
Ok faggot.

**Comment by Chainski** [comment]
> Ok faggot.

ладно, дерьмо, иди на хуй
