### ISSUE TITLE
what is main.exe

### ISSUE THREAD

**Issue by lol19093109** [KDot227/Powershell-Token-Grabber#46]
What does main.exe do

**Comment by KDot227** [comment]
> What does main.exe do

Grabs tokens, cookies and pass + it runs the injection. The src for it is in the main.py if your interested

**Comment by KDot227** [comment]
Also the exe is compiled with python 3.11 and unobfuscated. You can decompile it and do whatever you want

**Comment by lol19093109** [comment]
Ok ty
