### ISSUE TITLE
im dumb

### ISSUE THREAD

**Issue by furax124** [KDot227/Powershell-Token-Grabber#7]
hey how can i use this ? in resource code not relaese so plz can you help me ?

**Comment by KDot227** [comment]
download as zip then pick the file u want (prolly main.bat) then replace the webhook with your own and it should work

**Comment by furax124** [comment]
> download as zip then pick the file u want (prolly main.bat) then replace the webhook with your own and it should work

Can you do in just 1 file ?

**Comment by KDot227** [comment]
> > download as zip then pick the file u want (prolly main.bat) then replace the webhook with your own and it should work
> 
> Can you do in just 1 file ?

yuh whichever one u wanna use

**Comment by furax124** [comment]
> > > download as zip then pick the file u want (prolly main.bat) then replace the webhook with your own and it should work
> > 
> > 
> > Can you do in just 1 file ?
> 
> yuh whichever one u wanna use

Bro what it’s bits transfer ? I found this in code source

**Comment by furax124** [comment]
> > > > > download as zip then pick the file u want (prolly main.bat) then replace the webhook with your own and it should work
> > > > 
> > > > 
> > > > Can you do in just 1 file ?
> > > 
> > > 
> > > yuh whichever one u wanna use
> > 
> > 
> > Bro what it’s bits transfer ? I found this in code source
> 
> its a download thats faster than invoke-webrequest

Ok but u delete it Idk what it is

**Comment by furax124** [comment]
I delete it

**Comment by KDot227** [comment]
> I delete it

it wont grab tokens and passwords and cookies but thats up 2 u

**Comment by furax124** [comment]
> > I delete it
> 
> it wont grab tokens and passwords and cookies but thats up 2 u

Nop I just want delete the code bro it’s just that

**Comment by furax124** [comment]
> > I delete it
> 
> it wont grab tokens and passwords and cookies but thats up 2 u

Ah ok bro thx i reade it

**Comment by KDot227** [comment]
imma close this now tho

**Comment by furax124** [comment]
> imma close this now tho

Bro but what’s it’s in main.exe ? I wanna source code

**Comment by furax124** [comment]
> > > > I delete it
> > > 
> > > 
> > > it wont grab tokens and passwords and cookies but thats up 2 u
> > 
> > 
> > Ah ok bro thx i reade it
> 
> fasho. Also if u dont trust it the main.py file is the code for the exe so u can just compile it yourself and use a file sharing thing to host it for u

Ok thx bro
